/**
 * Generated by orval v8.13.0 🍺
 * Do not edit manually.
 * React CS Example
 * OpenAPI for example of React Cost Savings Component
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  BadRequestResponse,
  ListTodoParams,
  ListTodoResponse,
  NotFoundResponse,
  Todo,
  TodoRegistration,
} from "../models";

import { backendCustomInstance } from "../../backend/customInstance";
import type { ErrorType } from "../../backend/customInstance";

/**
 * List todo
 * @summary List todo
 */
export const listTodo = (params?: ListTodoParams, signal?: AbortSignal) => {
  return backendCustomInstance<ListTodoResponse>({
    url: `/todos`,
    method: "GET",
    params,
    signal,
  });
};

export const getListTodoQueryKey = (params?: ListTodoParams) => {
  return [`/todos`, ...(params ? [params] : [])] as const;
};

export const getListTodoQueryOptions = <
  TData = Awaited<ReturnType<typeof listTodo>>,
  TError = ErrorType<BadRequestResponse>,
>(
  params?: ListTodoParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listTodo>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListTodoQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listTodo>>> = ({
    signal,
  }) => listTodo(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listTodo>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type ListTodoQueryResult = NonNullable<
  Awaited<ReturnType<typeof listTodo>>
>;
export type ListTodoQueryError = ErrorType<BadRequestResponse>;

export function useListTodo<
  TData = Awaited<ReturnType<typeof listTodo>>,
  TError = ErrorType<BadRequestResponse>,
>(
  params: undefined | ListTodoParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listTodo>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTodo>>,
          TError,
          Awaited<ReturnType<typeof listTodo>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useListTodo<
  TData = Awaited<ReturnType<typeof listTodo>>,
  TError = ErrorType<BadRequestResponse>,
>(
  params?: ListTodoParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listTodo>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTodo>>,
          TError,
          Awaited<ReturnType<typeof listTodo>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useListTodo<
  TData = Awaited<ReturnType<typeof listTodo>>,
  TError = ErrorType<BadRequestResponse>,
>(
  params?: ListTodoParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listTodo>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary List todo
 */

export function useListTodo<
  TData = Awaited<ReturnType<typeof listTodo>>,
  TError = ErrorType<BadRequestResponse>,
>(
  params?: ListTodoParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listTodo>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getListTodoQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Create todo
 * @summary Create todo
 */
export const postTodo = (
  todoRegistration?: TodoRegistration,
  signal?: AbortSignal,
) => {
  return backendCustomInstance<Todo>({
    url: `/todos`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: todoRegistration,
    signal,
  });
};

export const getPostTodoMutationOptions = <
  TError = ErrorType<BadRequestResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postTodo>>,
    TError,
    { data?: TodoRegistration },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postTodo>>,
  TError,
  { data?: TodoRegistration },
  TContext
> => {
  const mutationKey = ["postTodo"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postTodo>>,
    { data?: TodoRegistration }
  > = (props) => {
    const { data } = props ?? {};

    return postTodo(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostTodoMutationResult = NonNullable<
  Awaited<ReturnType<typeof postTodo>>
>;
export type PostTodoMutationBody = TodoRegistration | undefined;
export type PostTodoMutationError = ErrorType<BadRequestResponse>;

/**
 * @summary Create todo
 */
export const usePostTodo = <
  TError = ErrorType<BadRequestResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postTodo>>,
      TError,
      { data?: TodoRegistration },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postTodo>>,
  TError,
  { data?: TodoRegistration },
  TContext
> => {
  return useMutation(getPostTodoMutationOptions(options), queryClient);
};
/**
 * Get todo
 * @summary Get todo
 */
export const getTodo = (todoId: string, signal?: AbortSignal) => {
  return backendCustomInstance<Todo>({
    url: `/todos/${todoId}`,
    method: "GET",
    signal,
  });
};

export const getGetTodoQueryKey = (todoId: string) => {
  return [`/todos/${todoId}`] as const;
};

export const getGetTodoQueryOptions = <
  TData = Awaited<ReturnType<typeof getTodo>>,
  TError = ErrorType<NotFoundResponse>,
>(
  todoId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTodo>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTodoQueryKey(todoId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTodo>>> = ({
    signal,
  }) => getTodo(todoId, signal);

  return {
    queryKey,
    queryFn,
    enabled: todoId !== null && todoId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getTodo>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData>;
  };
};

export type GetTodoQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTodo>>
>;
export type GetTodoQueryError = ErrorType<NotFoundResponse>;

export function useGetTodo<
  TData = Awaited<ReturnType<typeof getTodo>>,
  TError = ErrorType<NotFoundResponse>,
>(
  todoId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTodo>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTodo>>,
          TError,
          Awaited<ReturnType<typeof getTodo>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetTodo<
  TData = Awaited<ReturnType<typeof getTodo>>,
  TError = ErrorType<NotFoundResponse>,
>(
  todoId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTodo>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTodo>>,
          TError,
          Awaited<ReturnType<typeof getTodo>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetTodo<
  TData = Awaited<ReturnType<typeof getTodo>>,
  TError = ErrorType<NotFoundResponse>,
>(
  todoId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTodo>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
/**
 * @summary Get todo
 */

export function useGetTodo<
  TData = Awaited<ReturnType<typeof getTodo>>,
  TError = ErrorType<NotFoundResponse>,
>(
  todoId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTodo>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetTodoQueryOptions(todoId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Update todo
 * @summary Update todo
 */
export const putTodo = (
  todoId: string,
  todoRegistration?: TodoRegistration,
  signal?: AbortSignal,
) => {
  return backendCustomInstance<Todo>({
    url: `/todos/${todoId}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: todoRegistration,
    signal,
  });
};

export const getPutTodoMutationOptions = <
  TError = ErrorType<NotFoundResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putTodo>>,
    TError,
    { todoId: string; data?: TodoRegistration },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putTodo>>,
  TError,
  { todoId: string; data?: TodoRegistration },
  TContext
> => {
  const mutationKey = ["putTodo"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putTodo>>,
    { todoId: string; data?: TodoRegistration }
  > = (props) => {
    const { todoId, data } = props ?? {};

    return putTodo(todoId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutTodoMutationResult = NonNullable<
  Awaited<ReturnType<typeof putTodo>>
>;
export type PutTodoMutationBody = TodoRegistration | undefined;
export type PutTodoMutationError = ErrorType<NotFoundResponse>;

/**
 * @summary Update todo
 */
export const usePutTodo = <
  TError = ErrorType<NotFoundResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putTodo>>,
      TError,
      { todoId: string; data?: TodoRegistration },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putTodo>>,
  TError,
  { todoId: string; data?: TodoRegistration },
  TContext
> => {
  return useMutation(getPutTodoMutationOptions(options), queryClient);
};
/**
 * Delete todo
 * @summary Delete todo
 */
export const deleteTodo = (todoId: string, signal?: AbortSignal) => {
  return backendCustomInstance<Todo>({
    url: `/todos/${todoId}`,
    method: "DELETE",
    signal,
  });
};

export const getDeleteTodoMutationOptions = <
  TError = ErrorType<NotFoundResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteTodo>>,
    TError,
    { todoId: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteTodo>>,
  TError,
  { todoId: string },
  TContext
> => {
  const mutationKey = ["deleteTodo"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteTodo>>,
    { todoId: string }
  > = (props) => {
    const { todoId } = props ?? {};

    return deleteTodo(todoId);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteTodoMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteTodo>>
>;

export type DeleteTodoMutationError = ErrorType<NotFoundResponse>;

/**
 * @summary Delete todo
 */
export const useDeleteTodo = <
  TError = ErrorType<NotFoundResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteTodo>>,
      TError,
      { todoId: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteTodo>>,
  TError,
  { todoId: string },
  TContext
> => {
  return useMutation(getDeleteTodoMutationOptions(options), queryClient);
};
