/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * React CS Example
 * OpenAPI for example of React Cost Savings Component
 * OpenAPI spec version: 1.0.0
 */
import { HttpResponse, delay, http } from "msw";
import type { ListTodoResponse, Todo } from ".././model";
import { response200Default as listTodoResponse200Default } from "./responses/listTodo/response200Default";
import { response200Default as postTodoResponse200Default } from "./responses/postTodo/response200Default";
import { response200Default as putTodoResponse200Default } from "./responses/putTodo/response200Default";
import { response204Default as deleteTodoResponse204Default } from "./responses/deleteTodo/response204Default";
import { response200Default as getTodoResponse200Default } from "./responses/getTodo/response200Default";

export const getListTodoMockHandler = (
  overrideResponse?:
    | ListTodoResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ListTodoResponse> | ListTodoResponse),
  delayTime: number = 1000,
) => {
  return http.get("http://localhost:8080/todos", async (info) => {
    await delay(delayTime);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : listTodoResponse200Default.body,
      ),
      listTodoResponse200Default.init,
    );
  });
};

export const getPostTodoMockHandler = (
  overrideResponse?:
    | Todo
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<Todo> | Todo),
  delayTime: number = 1000,
) => {
  return http.post("http://localhost:8080/todos", async (info) => {
    await delay(delayTime);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : postTodoResponse200Default.body,
      ),
      postTodoResponse200Default.init,
    );
  });
};

export const getGetTodoMockHandler = (
  overrideResponse?:
    | Todo
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<Todo> | Todo),
  delayTime: number = 1000,
) => {
  return http.get("http://localhost:8080/todos/:todoId", async (info) => {
    await delay(delayTime);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getTodoResponse200Default.body,
      ),
      getTodoResponse200Default.init,
    );
  });
};

export const getPutTodoMockHandler = (
  overrideResponse?:
    | Todo
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Promise<Todo> | Todo),
  delayTime: number = 1000,
) => {
  return http.put("http://localhost:8080/todos/:todoId", async (info) => {
    await delay(delayTime);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : putTodoResponse200Default.body,
      ),
      putTodoResponse200Default.init,
    );
  });
};

export const getDeleteTodoMockHandler = (
  overrideResponse?:
    | Todo
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<Todo> | Todo),
  delayTime: number = 1000,
) => {
  return http.delete("http://localhost:8080/todos/:todoId", async (info) => {
    await delay(delayTime);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : deleteTodoResponse204Default.body,
      ),
      deleteTodoResponse204Default.init,
    );
  });
};

export const getTodosMock = () => [
  getListTodoMockHandler(),
  getPostTodoMockHandler(),
  getGetTodoMockHandler(),
  getPutTodoMockHandler(),
  getDeleteTodoMockHandler(),
];
