/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * React CS Example
 * OpenAPI for example of React Cost Savings Component
 * OpenAPI spec version: 1.0.0
 */
import type { ListTodoResponse, Todo } from ".././model";
import { listTodoResponse200Default } from "./responses/listTodo/listTodoResponse200Default";
import { postTodoResponse200Default } from "./responses/postTodo/postTodoResponse200Default";
import { putTodoResponse200Default } from "./responses/putTodo/putTodoResponse200Default";
import { deleteTodoResponse204Default } from "./responses/deleteTodo/deleteTodoResponse204Default";
import { getTodoResponse200Default } from "./responses/getTodo/getTodoResponse200Default";
import { createMockHandlerFactory } from "@/libs/api/msw/createMockHandlerFactory";
import { createRestResourceHandlers } from "@/libs/api/msw/createRestResourceHandlers";

export const getListTodoMockHandler =
  createMockHandlerFactory<ListTodoResponse>(
    "get",
    "http://localhost:8080/todos",
    listTodoResponse200Default,
  );

export const getPostTodoMockHandler = createMockHandlerFactory<Todo>(
  "post",
  "http://localhost:8080/todos",
  postTodoResponse200Default,
);

export const getGetTodoMockHandler = createMockHandlerFactory<Todo>(
  "get",
  "http://localhost:8080/todos/:todoId",
  getTodoResponse200Default,
);

export const getPutTodoMockHandler = createMockHandlerFactory<Todo>(
  "put",
  "http://localhost:8080/todos/:todoId",
  putTodoResponse200Default,
);

export const getDeleteTodoMockHandler = createMockHandlerFactory<Todo>(
  "delete",
  "http://localhost:8080/todos/:todoId",
  deleteTodoResponse204Default,
);

/**
 * Todoリソースのモックハンドラーを生成
 * RESTful APIパターンを使用し、/todosパスに対して統一されたデータストアを使用
 */
export const getTodosMock = () => {
  return createRestResourceHandlers<Todo, ListTodoResponse>({
    basePath: "/todos",
    idParam: "todoId",
    initialData: listTodoResponse200Default.body,
    handlers: {
      list: getListTodoMockHandler,
      create: getPostTodoMockHandler,
      get: getGetTodoMockHandler,
      update: getPutTodoMockHandler,
      delete: getDeleteTodoMockHandler,
    },
    // オプション: リスト取得時のフィルター処理
    filterFn: (data, searchParams) => {
      const assigneeEq = searchParams.get("assignee_eq");
      if (assigneeEq) {
        return data.filter((todo) => todo.assignee === assigneeEq);
      }
      return data;
    },
  });
};
