/**
 * Generated by orval v8.13.0 🍺
 * Do not edit manually.
 * React CS Example
 * OpenAPI for example of React Cost Savings Component
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorResponse } from "./errorResponse";

/**
 * Bad Request
 */
export type BadRequestResponse = ErrorResponse;
