/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * React CS Example
 * OpenAPI for example of React Cost Savings Component
 * OpenAPI spec version: 1.0.0
 */

/**
 * Todo
 */
export interface Todo {
  /** Todo assignee */
  assignee: string;
  /** Todo description */
  description: string;
  /** Todo Id */
  id: string;
  /** Todo title */
  title: string;
}
